# Generated by Django 5.2.11 on 2026-02-04 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название бригады')),
                ('brigadier', models.CharField(max_length=255, verbose_name='Бригадир')),
                ('responsible', models.CharField(max_length=255, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Бригада',
                'verbose_name_plural': 'Бригады',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Серийный номер')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Бренд')),
                ('status', models.CharField(choices=[('at_work', 'В работе'), ('in_repair', 'В ремонте'), ('issued', 'Выдано'), ('available', 'Доступно'), ('confirm', 'Подтвердить ТМЦ'), ('confirm_repair', 'Подтвердить ремонт')], default='available', max_length=20, verbose_name='Статус')),
                ('responsible', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ответственный')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Локация')),
                ('qty', models.IntegerField(default=1, verbose_name='Количество')),
                ('brigade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.brigade', verbose_name='Закрепленная бригада')),
            ],
            options={
                'verbose_name': 'ТМЦ',
                'verbose_name_plural': 'ТМЦ',
            },
        ),
    ]
