# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Серийный номер')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Бренд')),
                ('status', models.CharField(choices=[('at_work', 'В работе'), ('in_repair', 'В ремонте'), ('issued', 'Выдано'), ('available', 'Доступно'), ('confirm', 'Подтвердить ТМЦ'), ('confirm_repair', 'Подтвердить ремонт')], default='available', max_length=20, verbose_name='Статус')),
                ('responsible', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ответственный')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Локация')),
                ('qty', models.IntegerField(default=1, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'ТМЦ',
                'verbose_name_plural': 'ТМЦ',
            },
        ),
    ]

