# Generated by Django 5.2.11 on 2026-02-11 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название бригады')),
                ('brigadier', models.CharField(max_length=255, verbose_name='Бригадир')),
                ('responsible', models.CharField(max_length=255, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Бригада',
                'verbose_name_plural': 'Бригады',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'verbose_name': 'Локация',
                'verbose_name_plural': 'Локации',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Серийный номер')),
                ('brand', models.CharField(blank=True, max_length=100, null=True, verbose_name='Бренд')),
                ('status', models.CharField(choices=[('created', 'Создано'), ('at_work', 'В работе'), ('in_repair', 'В ремонте'), ('issued', 'Выдано'), ('available', 'Доступно'), ('confirm', 'Требует подтверждения'), ('confirm_repair', 'Подтвердить ремонт'), ('written_off', 'Списано')], default='available', max_length=20, verbose_name='Статус')),
                ('responsible', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ответственный')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Локация')),
                ('qty', models.IntegerField(default=1, verbose_name='Количество')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='Время блокировки')),
                ('brigade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.brigade', verbose_name='Закрепленная бригада')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Заблокировано пользователем')),
            ],
            options={
                'verbose_name': 'ТМЦ',
                'verbose_name_plural': 'ТМЦ',
            },
        ),
        migrations.CreateModel(
            name='ItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('action_type', models.CharField(blank=True, choices=[('accepted', 'ТМЦ принято'), ('rejected', 'ТМЦ не принято'), ('sent_to_service', 'Отправлено в сервис'), ('returned_from_service', 'Возвращено из сервиса'), ('repair_confirmed', 'Ремонт подтверждён'), ('updated', 'Обновление информации'), ('status_changed', 'Смена статуса'), ('locked', 'Заблокировано'), ('unlocked', 'Разблокировано'), ('assigned', 'ТМЦ распределено'), ('confirmed', 'ТМЦ подтверждено')], max_length=50, null=True, verbose_name='Тип действия')),
                ('payload', models.JSONField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='items.item')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='items.location', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'История ТМЦ',
                'verbose_name_plural': 'История ТМЦ',
                'ordering': ['-timestamp'],
            },
        ),
    ]
