# Generated by Django 5.2.11 on 2026-02-12 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Заблокировано пользователем'),
        ),
        migrations.AddField(
            model_name='itemhistory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='items.item'),
        ),
        migrations.AddField(
            model_name='itemhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='itemhistory',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='items.location', verbose_name='Локация'),
        ),
        migrations.AddField(
            model_name='writeoffrecord',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_off_records', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал запись'),
        ),
        migrations.AddField(
            model_name='writeoffrecord',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_off_records', to='items.item', verbose_name='ТМЦ'),
        ),
        migrations.AddField(
            model_name='writeoffrecord',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='write_off_records', to='items.location', verbose_name='Локация списания'),
        ),
        migrations.AddConstraint(
            model_name='writeoffrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cancelled', False)), fields=('item', 'is_cancelled'), name='unique_active_write_off_per_item'),
        ),
    ]
