# Generated by Django 5.2.11 on 2026-02-10 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_itemhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время блокировки'),
        ),
        migrations.AddField(
            model_name='item',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Заблокировано пользователем'),
        ),
        # migrations.AddField(
        #     model_name='itemhistory',
        #     name='comment',
        #     field=models.TextField(blank=True, null=True),
        # ),
    ]
