# Generated by Django 5.2.11 on 2026-02-12 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemhistory',
            name='action_type',
            field=models.CharField(blank=True, choices=[('accepted', 'ТМЦ принято'), ('rejected', 'ТМЦ не принято'), ('sent_to_service', 'Отправлено в сервис'), ('returned_from_service', 'Возвращено из сервиса'), ('repair_confirmed', 'Ремонт подтверждён'), ('updated', 'Обновление информации'), ('status_changed', 'Смена статуса'), ('locked', 'Заблокировано'), ('unlocked', 'Разблокировано'), ('assigned', 'ТМЦ распределено'), ('confirmed', 'ТМЦ подтверждено'), ('written_off', 'Списано'), ('cancelled_write_off', 'Отмена списания')], max_length=50, null=True, verbose_name='Тип действия'),
        ),
        migrations.AlterField(
            model_name='writeoffrecord',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='write_off_records', to='items.location', verbose_name='Локация списания'),
        ),
    ]
