# Generated by Django 5.2.11 on 2026-02-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_itemhistory_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Количество'),
        ),
    ]
