# Generated by Django 5.2.11 on 2026-02-18 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_add_service_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время ошибки')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('message', models.TextField(verbose_name='Сообщение об ошибке')),
                ('stack_trace', models.TextField(verbose_name='Stack trace')),
                ('user_agent', models.CharField(max_length=255, verbose_name='User Agent')),
                ('resolved', models.BooleanField(default=False, verbose_name='Исправлено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог ошибки',
                'verbose_name_plural': 'Логи ошибок',
                'ordering': ['-timestamp'],
            },
        ),
    ]
