# Generated by Django 5.2.11 on 2026-03-03 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время входа')),
                ('username', models.CharField(max_length=150, verbose_name='Логин пользователя')),
                ('success', models.BooleanField(verbose_name='Успешный вход')),
                ('error_status', models.CharField(blank=True, choices=[('invalid_password', 'Неверный пароль'), ('invalid_username', 'Неверный логин'), ('user_blocked', 'Пользователь заблокирован'), ('user_inactive', 'Пользователь неактивен'), ('unknown', 'Неизвестная ошибка')], max_length=30, null=True, verbose_name='Статус ошибки')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User Agent')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог входов',
                'verbose_name_plural': 'Логи входов',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='users_login_timesta_f4a43d_idx'), models.Index(fields=['username'], name='users_login_usernam_b31f5e_idx'), models.Index(fields=['user', '-timestamp'], name='users_login_user_id_c46dab_idx')],
            },
        ),
    ]
