# Generated by Django 5.2.11 on 2026-03-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_loginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='ip_debug',
            field=models.TextField(blank=True, verbose_name='Отладка IP'),
        ),
    ]
