# Generated by Django 5.2.11 on 2026-03-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_active_user_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='token_id',
            field=models.CharField(max_length=512, unique=True, verbose_name='ID токена'),
        ),
    ]
