# Generated by Django 5.2.11 on 2026-03-03 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_loginlog_ip_debug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginlog',
            name='ip_debug',
        ),
    ]
