# Generated by Django 5.2.11 on 2026-02-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usersession_token_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Режим обслуживания включён')),
                ('planned_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Планируемое время завершения')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Режим обслуживания',
                'verbose_name_plural': 'Режимы обслуживания',
            },
        ),
    ]
