# Generated by Django 5.2.11 on 2026-03-02 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usersession_token_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(verbose_name='Refresh токен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('expires_at', models.DateTimeField(verbose_name='Время истечения токена')),
                ('reason', models.CharField(default='admin_terminated', max_length=100, verbose_name='Причина')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отозванный токен',
                'verbose_name_plural': 'Отозванные токены',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='users_token_user_id_8c0dcf_idx'), models.Index(fields=['expires_at'], name='users_token_expires_7c745a_idx')],
            },
        ),
    ]
