# Generated by Django 5.2.11 on 2026-03-02 11:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_tokenblacklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='session_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name='UUID сессии'),
        ),
    ]
