# Generated by Django 5.2.11 on 2026-03-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_maintenancemode'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancemode',
            name='allowed_ips',
            field=models.JSONField(default=list, help_text='Список IP-адресов, которые имеют доступ во время обслуживания', verbose_name='Разрешённые IP-адреса'),
        ),
        migrations.AddField(
            model_name='maintenancemode',
            name='allowed_urls',
            field=models.JSONField(default=list, help_text='Список URL (regex), которые доступны во время обслуживания', verbose_name='Разрешённые URL'),
        ),
    ]
